name: Continuous integration

on: [pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Create npm configuration
        run: echo "//npm.pkg.github.com/:_authToken=${token}" >> ~/.npmrc
        env:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run lint
      - run: npm run build
      - run: npm run test

  install_from_tool_cache:
    needs: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - ubuntu-16.04
          - macOS-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install sccache
        uses: ./
        with:
          crate: sccache
          use-tool-cache: true
      - run: sccache --help

  disabled_tool_cache:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install sccache
        uses: ./
        with:
          crate: sccache
      - run: sccache --help

  install_missing_from_tool_cache:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install bat
        uses: ./
        with:
          crate: bat
          use-tool-cache: true
      - run: bat package.json
