name: Continuous integration

on: [pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Create npm configuration
        run: echo "//npm.pkg.github.com/:_authToken=${token}" >> ~/.npmrc
        env:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run lint
      - run: npm run build
      - run: npm run test

  install_with_cache:
    needs: test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - ubuntu-16.04
          - macOS-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install sccache
        uses: ./
        with:
          crate: sccache
      - run: sccache --help
      # Second execution should have cache filled
      - name: Install sccache
        uses: ./
        with:
          crate: sccache

  multiple_binary_targets:
    needs: test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install wasm-bindgen-cli
        uses: ./
        with:
          crate: wasm-bindgen-cli
          version: 0.2.60
      - run: test -f ~/.cargo/bin/wasm-bindgen
        shell: bash
