name: Continuous integration

on: [pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Create npm configuration
        run: echo "//npm.pkg.github.com/:_authToken=${token}" >> ~/.npmrc
        env:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run lint
      - run: npm run build
      - run: npm run test

  install_from_tool_cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          crate: cross
      # To this point `cross` should be available
      # and `cargo` command will not attempt to install it once again
      - uses: actions-rs/cargo@v1
        with:
          command: check
          use-cross: true

  install_missing_from_tool_cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          crate: bat
      - run: bat package.json
