name: Continuous integration

on: [pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Create npm configuration
        run: echo "//npm.pkg.github.com/:_authToken=${token}" >> ~/.npmrc
        env:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run lint
      - run: npm run build
      - run: npm run test

  install:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        crate:
          - cross  # Available in the tool cache
          - ripgrep  # Not available in the tool cache
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          crate: ${{ matrix.crate }}
